language: python

python:
  - 3.6
# versions of python we are running tests on

install: skip

cache: pip
# cache content that does not often change, to speed up your build process. 

script: python app_test.py # run tests
